### ISSUE TITLE
"No such file or directory" error occurred when creating ClusterAdmissionPolicy

### ISSUE THREAD

**Issue by agilemeng** [kubewarden/helm-charts#116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Install the latest kubewarden and create a policy file as follows：
`apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: privileged-pods
spec:
  policyServer: default
  module: file:///test/policy.wasm
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations:
        - CREATE
        - UPDATE
  mutating: false`
The wasm policy file has been downloaded and placed on the host.

### Expected Behavior

Policy successfully created

### Environment

```markdown
- OS:Linux
- Architecture:x86
```

### Anything else?

Is there something wrong with the way I use it? Who can tell me？

**Comment by jvanz** [comment]
Hi @agilemeng ! Thank you for the reporting. 

I have some difficulties to understand the issue. Can I ask some questions?

Is the error in the issue description from the output of the helm installation process or when you try to install a policy from a separate yaml file? If it is from a separate yaml file, can you share the file?

Furthermore, I can see from the error message that you are using the CRDs version `policies.kubewarden.io/v1alpha2`. We already release the `v1` can you update and test it?

**Comment by jvanz** [comment]
Furthermore, can you share the command (or commands) that you are executing to cause the issue?

**Comment by viccuad** [comment]
> The wasm policy file has been downloaded and placed on the host.
> [...]
> module: file:///test/policy.wasm

From this, I understand that you are trying to load the policy from inside the Kubernetes node?

Kubewarden policies are Wasm modules, and, just like container images, they are fully supported by OCI registries. They can be pushed and pulled from the registry.

If you are trying to load policies directly via `file://`  instead of `registry://` in the policy-server pod, you will need to add a HostPath Volume mount. But it really is easier to just consume the policies from a registry, just the same way that one consumes container images from the registry instead of pre-loading them in the k8s nodes.

I think this is an [XY problem](https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem): May I ask what are you really trying to achieve here?

**Comment by agilemeng** [comment]
Thanks, I will try again.

**Comment by agilemeng** [comment]
Thanks, I will try again
