### ISSUE TITLE
helm charts: evaluate creation of SBOM files

### ISSUE THREAD

**Issue by flavio** [kubewarden/helm-charts#120]
Each release should have a SBOM file that allows to track the origin of all the dependencies.

It looks like this project can do it: https://github.com/defenseunicorns/sbom-cli

Acceptance criteria:

* Figure out if it make sense (from a technical POV) to have SBOM files for helm charts (are they a real thing?)
* Implement creation of SBOM files

**Comment by raulcabello** [comment]
I don't find information about sbom for helm charts. In my opinion we don't need to create an sbom for helm charts.  https://github.com/defenseunicorns/sbom-cli seems to just add the images used in the chart to an sbom file, which are referenced by a new annotation. 
It's not possible to know which version of the `controller` or `policy-server` a user is going to use by looking at the helm chart, since it could be modified with the values.yaml or by using `--set`
I think having sbom for all projects is all we need.

**Comment by viccuad** [comment]
The CRDs come from `kubewarden-controller`, though. It would be good to know exactly from which tag/commit of `kubewarden-controller` come from. Maybe just a new makefile target for `make import-crds` that takes the crds from the latest public release and crafts a commit. If we want to use sbom tools, we can add `kubewarden-controller` repo as a git submodule, and call the bom tool.

All in all, pretty low gains.

**Comment by flavio** [comment]
Closing, as said above it there isn't anything we can do so far with that

**Comment by jvanz** [comment]
We could create a SBOM file with the files included in the helm chart release. As all the files have checksum, it will be possible to know which file version in use. Furthermore, I **guess** the SBOM file will include the git info in the file definition. Which also helps to detect which file is in the release.
